version: "3"

services:
  mongodb:
    image: mongo:4.4
    # command: ["mongod", "--storageEngine", "inMemory"]
    restart: always
    environment:
      MONGO_INIT_DB_ROOT_USERNAME: root
      MONGO_INIT_DB_ROOT_USERNAME: rootpw
    # volumes:
    #   - ./volumes/mongodb_config:/data/configdb
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3001:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpw
  
  app:
    build: build-src
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://mongodb:27017/some_random_db
    ports:
      - 3000:3000
    # command: npm run dev
    # volumes:
    #   - ./build-src/app:/app/
    #   - /app/node_modules
